/** Canonical origin, matching `public/CNAME`. Used to build shareable links. */
export const SITE_URL = "https://danavner.com";

export const SITE_NAME = "Dan Avner";

/** Fallback social image for pages that have no photo of their own. */
export const DEFAULT_SHARE_IMAGE = "/img/me1.jpg";

/**
 * Fallback for a show with no photos. A portrait is the right social image for
 * the site as a whole and the wrong one for a festival, where a link preview
 * showing a headshot reads as the wrong link entirely. Generated by
 * `scripts/make-share-fallback.mjs`.
 */
export const SHOW_FALLBACK_IMAGE = "/img/share-card.jpg";
