/** Canonical origin, matching `public/CNAME`. Used to build shareable links. */
export const SITE_URL = "https://danavner.com";

export const SITE_NAME = "Dan Avner";

/**
 * The site's sections, in nav order.
 *
 * One list because the header and the footer both render it, and they drifted
 * when they each kept their own - a section added to one is a section half the
 * site cannot reach.
 */
export const SECTIONS = [
  { to: "/now", label: "Now" },
  { to: "/about", label: "About" },
  { to: "/career", label: "Career" },
  { to: "/blog", label: "Blog" },
  { to: "/shows", label: "Shows" },
  { to: "/vinyl", label: "Vinyl" },
  { to: "/comics", label: "Comics" },
] as const;

/**
 * The site's own link-preview card: the wordmark and a line advertising the site
 * over a faded portrait, in the site's look. Used for the home page and any page
 * without a more specific image. Generated by `scripts/make-site-card.mjs`.
 */
export const DEFAULT_SHARE_IMAGE = "/img/og-card.jpg";

/**
 * Fallback for a show with no photos. A portrait is the right social image for
 * the site as a whole and the wrong one for a festival, where a link preview
 * showing a headshot reads as the wrong link entirely. Generated by
 * `scripts/make-share-fallback.mjs`.
 */
export const SHOW_FALLBACK_IMAGE = "/img/share-card.jpg";
