/** Canonical origin, matching `public/CNAME`. Used to build shareable links. */
export const SITE_URL = "https://danavner.com";

export const SITE_NAME = "Dan Avner";

/**
 * The one clock the site reads a date on.
 *
 * Fixed rather than the machine's, so every build stamps the same date whoever
 * makes it, and Pacific rather than UTC because the author writes from Pacific:
 * UTC files an evening commit, or a data job that commits in UTC, under
 * tomorrow's date, and a footer claiming a day the reader has not reached yet
 * reads as broken.
 *
 * It is the station's day on `/dan-fm` as well. "Today's album" has to mean the
 * same album everywhere, or a reader in Tokyo is told the station is off air
 * while it is playing - so the footer's date and the lamp measure a day the
 * same way, from here. Vite's config reads it too, which is why it lives beside
 * the nav rather than in the route that lights the lamp.
 */
export const SITE_TIME_ZONE = "America/Los_Angeles";

/**
 * How the now page describes itself, in one place.
 *
 * It is the page's lede, its meta description, and its blurb in the home index.
 * Kept here rather than in the route because the route is lazily loaded, and
 * importing a constant out of it would pull that whole chunk into the landing
 * page's bundle to read one sentence.
 */
export const NOW_DESCRIPTION =
  "What I'm doing at the moment, updated whenever it stops being true.";

export interface Section {
  to: string;
  label: string;
}

export interface SectionGroup {
  label: string;
  items: Section[];
}

/**
 * The site's sections, in nav order.
 *
 * One list because the header and the footer both render it; two lists drift,
 * and a section added to one is a section half the site cannot reach.
 *
 * The collections are grouped rather than sitting alongside About and Career,
 * because they are not the same kind of thing: Shows, Vinyl and Comics are all
 * "what I am into", and listing them flat makes a seven-item bar where four of
 * the entries answer the same question. Grouping also stops the bar growing
 * every time another shelf gets a page.
 */
export const SECTIONS: (Section | SectionGroup)[] = [
  { to: "/now", label: "Now" },
  { to: "/about", label: "About" },
  { to: "/career", label: "Career" },
  { to: "/blog", label: "Blog" },
  {
    label: "Hobbies",
    items: [
      { to: "/shows", label: "Shows" },
      { to: "/vinyl", label: "Vinyl" },
      { to: "/comics", label: "Comics" },
      { to: "/fortnite", label: "Fortnite" },
      { to: "/dan-fm", label: "dan.fm" },
    ],
  },
];

export function isGroup(entry: Section | SectionGroup): entry is SectionGroup {
  return "items" in entry;
}

/**
 * Every page, flattened. The footer lists them all rather than reproducing the
 * grouping - a footer is an index, and hiding three pages behind a heading there
 * would only make them harder to find.
 */
export const ALL_SECTIONS: Section[] = SECTIONS.flatMap((entry) =>
  isGroup(entry) ? entry.items : [entry],
);

/**
 * The site's own link-preview card: the wordmark and a line advertising the site
 * over a faded portrait, in the site's look. Used for the home page and any page
 * without a more specific image. Generated by `scripts/make-site-card.mjs`.
 */
export const DEFAULT_SHARE_IMAGE = "/img/og-card.jpg";

/**
 * Fallback for a show with no photos. A portrait is the right social image for
 * the site as a whole and the wrong one for a festival, where a link preview
 * showing a headshot reads as the wrong link entirely. Generated by
 * `scripts/make-share-fallback.mjs`.
 */
export const SHOW_FALLBACK_IMAGE = "/img/share-card.jpg";
